# Generated by Django 3.2.12 on 2022-05-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_score_unique vote'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='score',
            name='unique vote',
        ),
    ]
