# Generated by Django 3.2.12 on 2022-05-19 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=50)),
                ('내용', models.TextField()),
                ('생성시간', models.DateTimeField(auto_now_add=True)),
                ('업데이트시간', models.DateTimeField(auto_now=True)),
                ('글쓴이', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('영화', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('좋아요', models.ManyToManyField(related_name='like_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('내용', models.TextField()),
                ('생성시간', models.DateTimeField(auto_now_add=True)),
                ('업데이트시간', models.DateTimeField(auto_now=True)),
                ('글쓴이', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('리뷰', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.review')),
                ('좋아요', models.ManyToManyField(related_name='like_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
