# Generated by Django 3.2.12 on 2022-05-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='내용',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='생성시간',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='리뷰',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='업데이트시간',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='글쓴이',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='내용',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='생성시간',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='영화',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='제목',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='업데이트시간',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='글쓴이',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='좋아요',
        ),
        migrations.RemoveField(
            model_name='review',
            name='좋아요',
        ),
    ]
