# Generated by Django 3.2.12 on 2022-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20220519_1814'),
        ('movie', '0002_score'),
        ('accounts', '0003_auto_20220520_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_comments',
            field=models.ManyToManyField(related_name='like_people', to='community.Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(related_name='like_people', to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_reviews',
            field=models.ManyToManyField(related_name='like_people', to='community.Review'),
        ),
    ]
