# Generated by Django 3.2.12 on 2022-05-20 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220520_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='유저',
            new_name='user',
        ),
    ]
